config/routes.rb
Rails.application.routes.draw do

  devise_for :members, controllers: {
      sessions:      'members/sessions',
      passwords:     'members/passwords',
      registrations: 'members/registrations',
      confirmations: 'members/confirmations',
      omniauth_callbacks: 'members/omniauth_callbacks'
  }
  devise_scope :member do
    get '/members/sign_up/select', to: 'members/registrations#select'
    get '/members/sign_up/inactive', to: 'members/registrations#inactive'
    get '/members/signed_out', to: 'members/sessions#signed_out'
  end

  resources :items, only: [:index, :show]

  resources :carts, only: [:index, :create, :update, :destroy]
  namespace :order, path: 'order' do
    resources :purchases, only: [:new, :create] do
      member { get :complete }
    end
    resource :invoice_address, only: [:show, :create, :update]
    resources :delivery_addresses, only: [:index, :new, :create]
    resources :credit_cards, only: [:index, :new, :create]
    resources :guests, only: [:new, :create] do
      collection do
        get :sign_in
        post :confirm
      end
    end
  end

  resource :member, only: [:show, :update, :destroy] do
    collection do
      get :leave
      get :left
    end
  end
  namespace :member, path: 'member' do
    resources :favorites, only: [:index, :create, :destroy]
    resource :invoice_address, only: [:show, :create, :update]
    resources :delivery_addresses do
      member {post :change_main}
    end
    resources :credit_cards, only: [:index, :new, :create, :destroy] do
      member {post :change_main}
    end
    resources :purchases, only: [:index, :show]
  end

  resource :contacts, only: [:new, :create] do
    collection do
      post :confirm
      get :complete
    end
  end

  devise_for :managers, path: 'admin/manager', controllers: {
      sessions:      'admin/managers/sessions'
  }
  namespace :admin, path: 'admin' do
    resources :categories, except: :show
    resources :items, except: :show do
      collection { get :preview }
    end
    resources :purchases, only: [:index, :show, :update]
    resources :topics, except: :show
    resources :sliders, only: [:index, :edit, :update]
    resources :static_pages do
      collection { get :preview }
    end
    resources :contacts, only: [:index, :show, :destroy]
    resources :members, only: [:index, :show, :destroy]
    resources :managers, except: [:show]

    resources :images, only: [:new, :create]
    root 'top#index', as: :root
  end

  get 'static_pages/:name' => 'static_pages#show', as: :static_page

  # 郵便番号検索
  get 'postal_codes/:code' => 'postal_codes#show'
  post '/tinymce_assets' => 'admin/images#create'
  root 'top#index'
  get '*anything' => 'errors#routing_error'
end

app/views/admin/top.html.haml
.row
  .col-3
    .card
      = link_to admin_purchases_path(search: {purchased_at_from: Date.current.beginning_of_month}), class: 'text-white' do
        %h6.card-header.bg-info
          %i.fa.fa-yen
          今月の売上
          %i.fa.fa-angle-right.fa-lg.ml-1
      .card-body.text-center
        %p.m-0.lead= jpy(@current_month_purchase_summary, prefix: true)
  .col-3
    .card
      = link_to admin_purchases_path(search: {undelivered: '1'}), class: 'text-white' do
        %h6.card-header.bg-info
          %i.fa.fa-truck
          出荷待ち
          %i.fa.fa-angle-right.fa-lg.ml-2
      .card-body.text-center
        %p.m-0.lead
          = number_with_delimiter @undelivered_counts
          %span.small.text-muted 件
  .col-3
    .card
      %h6.card-header.bg-info
        %i.fa.fa-user
        会員数
      .card-body.text-center
        %p.m-0.lead
          = number_with_delimiter @member_counts
          %span.small.text-muted 人
  .col-3
    .card
      %h6.card-header.bg-info
        %i.fa.fa-cubes
        販売アイテム
      .card-body.text-center
        %p.m-0.lead
          = number_with_delimiter @selling_item_counts
          %span.small.text-muted 種類
.row
  .col-4
    .card
      = link_to admin_purchases_path(search: {purchased_at_from: Date.current - 6.days}), class: 'text-white' do
        %h6.card-header.bg-primary
          %i.fa.fa-shopping-cart
          一週間の売上
          %i.fa.fa-angle-right.fa-lg.ml-1
      %ul.list-group.list-group-flush
        - total_sales = total_count = 0
        - Date.current.downto(Date.current - 6.days).with_index do |date, i|
          :ruby
            summary = @recent_purchase_summaries.find{|summary| summary.purchased_date == date}
            if summary
              sales = summary.amount
              count = summary.count
              total_sales += sales
              total_count += count
            else
              sales = count = 0
            end
          = link_to admin_purchases_path(search: {purchased_at_from: date, purchased_at_to: date}) do
            %li.list-group-item
              .row
                .col-3.pr-0
                  %span.text-muted
                    - if i == 0
                      本日
                    - elsif i == 1
                      昨日
                    - else
                      = date.strftime('%m.%d')
                .col-9.pl-0
                  %p.text-right.lead.mb-0
                    = "#{jpy(sales, prefix: true)} / #{count}"
                    %span.small 件
        %li.list-group-item.bg-light
          .row
            .col-2.pr-0
              %span.text-muted 計
            .col-10.pl-0
              %p.text-right.lead.mb-0
                = "#{jpy(total_sales, prefix: true)} / #{total_count}"
                %span.small 件
  .col-8
    .card
      = link_to admin_items_path(search: {stock_quantity: 5, stock_type: :less, statuses: ['selling']}) do
        %h6.card-header.bg-warning
          %i.fa.fa-thermometer-empty
          在庫数が5以下の商品
          %i.fa.fa-angle-right.fa-lg.ml-1
      - if @limit_stock_items.size == 0
        .card-body ありません
      - else
        %ul.list-group.list-group-flush
          - @limit_stock_items.each do |item|
            = link_to edit_admin_item_path(item) do
              .row.py-2
                .col-2
                  = image_tag item.caption_image_url, class: 'img-fluid ml-2'
                .col-10
                  %span= item.name
                  %br/
                  %span= "残り#{item.stock_quantity}個"
    .card
      .card-header.bg-success
        %i.fa.fa-envelope
        新着お問い合わせ
        %i.fa.fa-angle-right.fa-lg.ml-1
      - if @unread_contacts.size == 0
        .card-body ありません
      - else
        .card-body.p-0
          %table.table.mb-0
            - @unread_contacts.each do |contact|
              %tr
                %td= contact.created_at.strftime('%m/%d %H:%M')
                %td= contact.last_name + ' 様'
                %td= contact.body.truncate(25)
                %td
                  = link_to admin_contact_path(contact) do
                    %i.fa.fa-angle-right