config/routes.rb
Rails.application.routes.draw do

  devise_for :members, controllers: {
      sessions:      'members/sessions',
      passwords:     'members/passwords',
      registrations: 'members/registrations',
      confirmations: 'members/confirmations',
      omniauth_callbacks: 'members/omniauth_callbacks'
  }
  devise_scope :member do
    get '/members/sign_up/select', to: 'members/registrations#select'
    get '/members/sign_up/inactive', to: 'members/registrations#inactive'
    get '/members/signed_out', to: 'members/sessions#signed_out'
  end

  resources :items, only: [:index, :show]

  resources :carts, only: [:index, :create, :update, :destroy]
  namespace :order, path: 'order' do
    resources :purchases, only: [:new, :create] do
      member { get :complete }
    end
    resource :invoice_address, only: [:show, :create, :update]
    resources :delivery_addresses, only: [:index, :new, :create]
    resources :credit_cards, only: [:index, :new, :create]
    resources :guests, only: [:new, :create] do
      collection do
        get :sign_in
        post :confirm
      end
    end
  end

  resource :member, only: [:show, :update, :destroy] do
    collection do
      get :leave
      get :left
    end
  end
  namespace :member, path: 'member' do
    resources :favorites, only: [:index, :create, :destroy]
    resource :invoice_address, only: [:show, :create, :update]
    resources :delivery_addresses do
      member {post :change_main}
    end
    resources :credit_cards, only: [:index, :new, :create, :destroy] do
      member {post :change_main}
    end
    resources :purchases, only: [:index, :show]
  end

  resource :contacts, only: [:new, :create] do
    collection do
      post :confirm
      get :complete
    end
  end

  devise_for :managers, path: 'admin/manager', controllers: {
      sessions:      'admin/managers/sessions'
  }
  namespace :admin, path: 'admin' do
    resources :categories, except: :show
    resources :items, except: :show do
      collection { get :preview }
    end
    resources :purchases, only: [:index, :show, :update]
    resources :topics, except: :show
    resources :sliders, only: [:index, :edit, :update]
    resources :static_pages do
      collection { get :preview }
    end
    resources :contacts, only: [:index, :show, :destroy]
    resources :members, only: [:index, :show, :destroy]
    resources :managers, except: [:show]

    resources :images, only: [:new, :create]
    root 'top#index', as: :root
  end

  get 'static_pages/:name' => 'static_pages#show', as: :static_page

  # 郵便番号検索
  get 'postal_codes/:code' => 'postal_codes#show'
  post '/tinymce_assets' => 'admin/images#create'
  root 'top#index'
  get '*anything' => 'errors#routing_error'
end

app/models/topic.rb
class Topic < ApplicationRecord
  validates :title, presence: true
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Admin::AdminBase
  def index
    @topics = Topic.all.page(params[:page]).per(30).order(id: :desc)
  end

  def new
    @topic = Topic.new
  end

  def create
    @topic = Topic.new(post_params)
    if @topic.save
      flash[:success] = '登録が完了しました'
      redirect_to admin_topics_path
    else
      flash.now[:error] = '入力内容をご確認ください'
      render :new
    end
  end

  def edit
    @topic = Topic.find(params[:id])
  end

  def update
    @topic = Topic.find(params[:id])
    @topic.assign_attributes(post_params)

    if @topic.save
      flash[:success] = '更新が完了しました'
      redirect_to admin_topics_path
    else
      flash.now[:error] = '入力内容をご確認ください'
      render :edit
    end
  end

  def destroy
    topic = Topic.find(params[:id])
    topic.destroy!
    flash[:success] = '削除が完了しました'
    redirect_to admin_topics_path
  end

  private
  def post_params
    params.require(:topic).permit(:title, :link_url)
  end
end

app/views/admin/topics/_form.html.haml
- label_class = 'col-sm-3 col-form-label text-right'
.form-group.row
  = f.label :title, class: "#{label_class} required"
  .col-sm-9
    = f.text_field :title, class: 'form-control'
    = error_label_tag(f.object, :title)
.form-group.row.link_area
  = f.label :link_url, class: label_class
  .col-sm-9
    = f.text_field :link_url, class: 'form-control'
    = error_label_tag(f.object, :link_url)

app/views/admin/topics/edit.html.haml
- @crumbs = [{title: 'トピック管理', path: admin_topics_path}, {title: @topic.title}]
= form_for @topic, url: admin_topic_path(@topic) do |f|
  .card
    .card-header
      トピック
    .card-body
      = render 'form', f: f
      .float-right
        = f.submit '更新', class: 'btn btn-primary mr-2'
        = link_to 'キャンセル', admin_topics_path, class: 'btn btn-light'

app/views/admin/topics/index.html.haml
- @crumbs = [{title: 'トピック管理'}]

.card
  .card-header.pt-3
    トピック一覧
    = link_to new_admin_topic_path, class: 'btn btn-success btn-sm float-right mb-0' do
      %i.fa.fa-plus
      新規作成
  .card-body
    %table.table.table-bordered.table-sm.table-hover
      %thead
        %tr.table-secondary
          %th{width: '20%'}= t('activerecord.attributes.created_at')
          %th{width: '65%'}= t('activerecord.attributes.topic.title')
          %th{width: '15%'}
      %tbody
        - @topics.each do |topic|
          %tr
            %td= topic.created_at.strftime('%Y/%m/%d %H:%M')
            %td= topic.title
            %td
              = link_to '編集', edit_admin_topic_path(topic)
              %span.my-2= '/'
              = link_to '削除', admin_topic_path(topic), method: :delete, data: {confirm: '削除してよろしいでしょうか？'}
    = paginate @topics

app/views/admin/topics/new.html.haml
- @crumbs = [{title: 'トピック管理', path: admin_topics_path}, {title: '新規作成'}]
= form_for @topic, url: admin_topics_path, method: :post do |f|
  .card
    .card-header
      トピック
    .card-body
      = render 'form', f: f
      .float-right
        = f.submit '登録', class: 'btn btn-primary mr-2'
        = link_to 'キャンセル', admin_topics_path, class: 'btn btn-light'