config/routes.rb
Rails.application.routes.draw do

  devise_for :members, controllers: {
      sessions:      'members/sessions',
      passwords:     'members/passwords',
      registrations: 'members/registrations',
      confirmations: 'members/confirmations',
      omniauth_callbacks: 'members/omniauth_callbacks'
  }
  devise_scope :member do
    get '/members/sign_up/select', to: 'members/registrations#select'
    get '/members/sign_up/inactive', to: 'members/registrations#inactive'
    get '/members/signed_out', to: 'members/sessions#signed_out'
  end

  resources :items, only: [:index, :show]

  resources :carts, only: [:index, :create, :update, :destroy]
  namespace :order, path: 'order' do
    resources :purchases, only: [:new, :create] do
      member { get :complete }
    end
    resource :invoice_address, only: [:show, :create, :update]
    resources :delivery_addresses, only: [:index, :new, :create]
    resources :credit_cards, only: [:index, :new, :create]
    resources :guests, only: [:new, :create] do
      collection do
        get :sign_in
        post :confirm
      end
    end
  end

  resource :member, only: [:show, :update, :destroy] do
    collection do
      get :leave
      get :left
    end
  end
  namespace :member, path: 'member' do
    resources :favorites, only: [:index, :create, :destroy]
    resource :invoice_address, only: [:show, :create, :update]
    resources :delivery_addresses do
      member {post :change_main}
    end
    resources :credit_cards, only: [:index, :new, :create, :destroy] do
      member {post :change_main}
    end
    resources :purchases, only: [:index, :show]
  end

  resource :contacts, only: [:new, :create] do
    collection do
      post :confirm
      get :complete
    end
  end

  devise_for :managers, path: 'admin/manager', controllers: {
      sessions:      'admin/managers/sessions'
  }
  namespace :admin, path: 'admin' do
    resources :categories, except: :show
    resources :items, except: :show do
      collection { get :preview }
    end
    resources :purchases, only: [:index, :show, :update]
    resources :topics, except: :show
    resources :sliders, only: [:index, :edit, :update]
    resources :static_pages do
      collection { get :preview }
    end
    resources :contacts, only: [:index, :show, :destroy]
    resources :members, only: [:index, :show, :destroy]
    resources :managers, except: [:show]

    resources :images, only: [:new, :create]
    root 'top#index', as: :root
  end

  get 'static_pages/:name' => 'static_pages#show', as: :static_page

  # 郵便番号検索
  get 'postal_codes/:code' => 'postal_codes#show'
  post '/tinymce_assets' => 'admin/images#create'
  root 'top#index'
  get '*anything' => 'errors#routing_error'
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :member
  belongs_to :item

  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 1 }, presence: true

  def self.add_item(item_id, member, cart_session_id)
    if member.present?
      cart = Cart.find_or_initialize_by(member: member, item_id: item_id)
    else
      cart = Cart.find_or_initialize_by(session_id: cart_session_id, item_id: item_id)
    end
    cart.quantity += 1
    if cart.item_error.present?
      return false
    else
      cart.save! && cart
    end
  end

  def update_quantity(quantity)
    self.quantity = quantity
    if self.item_error.present?
      false
    else
      self.save!
    end
  end

  def item_error
    return :item_end if self.item.end_of_sell?
    return :unpublished if self.item.unpublished?
    return :zero if self.item.stock_quantity == 0
    return :minus if self.quantity > self.item.stock_quantity
    nil
  end

  def self.current_quantity(member, cart_session_id)
    Cart.search(member, cart_session_id)&.sum(:quantity) || 0
  end

  def self.current_amount(member, cart_session_id)
    amount = 0
    Cart.search(member, cart_session_id)&.each do |cart|
      amount = amount + cart.item.price * cart.quantity
    end
    amount
  end

  def self.search(member, cart_session_id)
    if member.present?
      Cart.where(member: member)
    elsif cart_session_id.present?
      Cart.where(member: nil, session_id: cart_session_id)
    else
      nil
    end
  end

  def self.merge_session(member, cart_session_id)
    return if cart_session_id.blank?
    Cart.where(member: nil, session_id: cart_session_id).each do |session_cart|
      member_cart = Cart.find_or_initialize_by(member: member, item: session_cart.item)
      member_cart.quantity += session_cart.quantity
      member_cart.save!
      session_cart.destroy!
    end
  end

end

app/controllers/carts_controller.rb
class CartsController < FrontBase
  layout :set_layout
  before_action :find_cart, only: [:update, :destroy]

  def index
    if member_signed_in?
      @carts = current_member.carts.order(:id)
    else
      @carts = Cart.where(member: nil, session_id: cart_session_id).order(:id)
    end
  end

  def create
    if Cart.add_item(params[:item_id], current_member, cart_session_id)
      redirect_to item_path(id: params[:item_id], cart_added: true)
    else
      flash[:error] = 'カートに商品を追加することができませんでした。'
      redirect_to item_path(id: params[:item_id])
    end
  end

  def update
    if @cart.update_quantity(params[:cart][:quantity].to_i)
      flash[:success] = "#{@cart.item.name} の数量を変更しました。"
    else
      flash[:error] = '数量を変更することができません。'
    end

    redirect_to carts_path
  end

  def destroy
    @cart.destroy!
    flash[:success] = "#{@cart.item.name} はカートから削除されました。"
    redirect_to action: :index
  end

  private
  def set_layout
    if member_signed_in?
      'mypage'
    else
      'front'
    end
  end

  def cart_session_id
    if session[:cart_session_id].blank?
      session[:cart_session_id] = SecureRandom.uuid
    end
    session[:cart_session_id]
  end

  def find_cart
    if member_signed_in?
      @cart = current_member.carts.find(params[:id])
    else
      @cart = Cart.find_by(member: nil, session_id: cart_session_id)
      raise ActiveRecord::RecordNotFound if @cart.nil?
    end
  end
end

app/views/carts/_button.html.haml
- if item.can_sell?
  = link_to carts_path(item_id: item.id), method: :post, class: 'ml-2' do
    = button_tag class: "btn bmd-btn-fab btn-warning #{btn_size}", 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', title: 'カートに追加する' do
      %i.material-icons add_shopping_cart

app/views/carts/index.html.haml
- content_for :stylesheet do
  = stylesheet_link_tag 'front/cart'
.container.cart_index
  - flash_messages
  - if @carts.size == 0
    .alert.alert-primary カートに商品がありません
    .text-center
      = link_to '商品を探す', items_path, class: 'btn btn-info btn-raised'
  - else
    - @carts.each do |cart|
      - item_error = cart.item_error
      - if item_error.present?
        .alert.alert-warning
          = "#{cart.item.name}は販売終了となりました。申し訳ございませんが、カートから削除してください。" if item_error == :item_end
          = "#{cart.item.name}は一時的に在庫切れとなっています。申し訳ございませんが、カートから削除してください。" if item_error == :zero
          = "#{cart.item.name}は残り#{cart.item.stock_quantity}点となりました。申し訳ございませんが、数量を変更してください。" if item_error == :minus
    .jumbotron
      - unless member_signed_in?
        %h3.text-center.mb-3 ショッピングカート
      .text-center
        %h5.mb-3
          = "合計（#{Cart.current_quantity(current_member, session[:cart_session_id])}点）:#{jpy(Cart.current_amount(current_member, session[:cart_session_id]), prefix: true, tax: :exclude)}"
        = link_to new_order_purchase_path, class: 'btn btn-warning btn-raised mx-1' do
          %i.fa.fa-arrow-right
          レジへ進む
        = link_to 'お買い物を続ける', items_path, class: 'btn btn-outline-secondary mx-1'
    .card
      .card-body.py-0
        %table.table.cart_list.table-hover.mb-0
          %thead
            %tr
              %th.text-center 削除
              %th{colspan: 2} 商品
              %th 数量
          %tbody
            - @carts.each do |cart|
              %tr{class: "#{'table-warning' if cart.item_error.present?}"}
                %td.text-center
                  = link_to cart_path(cart), method: :delete, data: {confirm: 'カートから削除してよろしいでしょうか？'} do
                    %i.fa.fa-times.fa-lg
                %td.img_td
                  = link_to item_path(cart.item) do
                    = image_tag cart.item.caption_image_url
                %td
                  = link_to item_path(cart.item) do
                    %h4.item_title= cart.item.name
                  %p.text-muted= jpy(cart.item.price, prefix: true)
                  %p.view_pc= cart.item.description
                %td
                  = form_for cart, url: cart_path(cart), class: 'form-inline' do |f|
                    = f.select :quantity, options_for_select(1..ceil_cart_quantity(cart), selected: cart.quantity), {include_blank: cart.item_error.present?}, {class: 'form-control quantity_select'}
- content_for :javascript do
  :javascript
    $(document).ready(function(){
       $('.quantity_select').change(function() {
           $(this).parents('form').submit();
       })
    });