config/routes.rb
Rails.application.routes.draw do

  devise_for :members, controllers: {
      sessions:      'members/sessions',
      passwords:     'members/passwords',
      registrations: 'members/registrations',
      confirmations: 'members/confirmations',
      omniauth_callbacks: 'members/omniauth_callbacks'
  }
  devise_scope :member do
    get '/members/sign_up/select', to: 'members/registrations#select'
    get '/members/sign_up/inactive', to: 'members/registrations#inactive'
    get '/members/signed_out', to: 'members/sessions#signed_out'
  end

  resources :items, only: [:index, :show]

  resources :carts, only: [:index, :create, :update, :destroy]
  namespace :order, path: 'order' do
    resources :purchases, only: [:new, :create] do
      member { get :complete }
    end
    resource :invoice_address, only: [:show, :create, :update]
    resources :delivery_addresses, only: [:index, :new, :create]
    resources :credit_cards, only: [:index, :new, :create]
    resources :guests, only: [:new, :create] do
      collection do
        get :sign_in
        post :confirm
      end
    end
  end

  resource :member, only: [:show, :update, :destroy] do
    collection do
      get :leave
      get :left
    end
  end
  namespace :member, path: 'member' do
    resources :favorites, only: [:index, :create, :destroy]
    resource :invoice_address, only: [:show, :create, :update]
    resources :delivery_addresses do
      member {post :change_main}
    end
    resources :credit_cards, only: [:index, :new, :create, :destroy] do
      member {post :change_main}
    end
    resources :purchases, only: [:index, :show]
  end

  resource :contacts, only: [:new, :create] do
    collection do
      post :confirm
      get :complete
    end
  end

  devise_for :managers, path: 'admin/manager', controllers: {
      sessions:      'admin/managers/sessions'
  }
  namespace :admin, path: 'admin' do
    resources :categories, except: :show
    resources :items, except: :show do
      collection { get :preview }
    end
    resources :purchases, only: [:index, :show, :update]
    resources :topics, except: :show
    resources :sliders, only: [:index, :edit, :update]
    resources :static_pages do
      collection { get :preview }
    end
    resources :contacts, only: [:index, :show, :destroy]
    resources :members, only: [:index, :show, :destroy]
    resources :managers, except: [:show]

    resources :images, only: [:new, :create]
    root 'top#index', as: :root
  end

  get 'static_pages/:name' => 'static_pages#show', as: :static_page

  # 郵便番号検索
  get 'postal_codes/:code' => 'postal_codes#show'
  post '/tinymce_assets' => 'admin/images#create'
  root 'top#index'
  get '*anything' => 'errors#routing_error'
end

app/models/image.rb
class Image < ApplicationRecord

  attr_accessor :target_class

  validates :image_file_name, presence: true

  if Rails.env.development?
    has_attached_file :image,
                      :styles => { :caption => '450x300#', :thumb => '150x150#' },
                      :url  => '/assets/paperclip/:id/:style.:extension',
                      :path => "#{Rails.root}/public/assets/paperclip/:id/:style.:extension"
  else
    has_attached_file :image,
                      :styles => { :caption => '450x300#', :thumb => '150x150#' },
                      :default_url => '/images/:style/missing.png',
                      :storage => :s3,
                      :bucket => ENV['S3_BUCKET'],
                      :s3_region => ENV['S3_REGION'],
                      :s3_host_name => ENV['S3_HOST'],
                      :s3_permissions => 'public-read',
                      :s3_credentials => "#{Rails.root}/config/s3.yml",
                      :path => '/images/:id/:style.:extension'
  end

  validates_attachment_content_type :image,
                                    :content_type => %W{image/jpg image/jpeg image/png image/x-png image/gif},
                                    :message => '画像以外のファイルが選択されています'

  validates_attachment_size :image, :less_than => 3.megabytes,
                            :message => 'ファイルサイズは3MB以内にしてください'

  def public_url(style = :original)
    if Rails.env.development?
      image.url(style)
    else
      image.s3_object(style).public_url
    end
  end

end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::AdminBase

  def new
    @image = Image.new
    @image.target_class = params[:target_class]
    respond_to {|format| format.js}
  end

  def create
    image = Image.new(image: params[:file])

    if image.save
      render json: {
          image: {
              url: image.public_url(params[:size_type]).to_s,
              id: image.id.to_s,
              width: '100%'
          }
      }, content_type: 'text/html'
    else
      render json: {
          error_message: image.errors.messages[0]
      }, content_type: 'text/html'
    end
  end

  private
  def post_params
    params.require(:image).permit(:image, :target_class)
  end
end

app/views/admin/images/_new.html.haml
.modal.fade#image_select_dialog
  .modal-dialog
    .modal-content
      .modal-header
        %h5.modal-title ファイル選択
        %button.close{'aria-label' => 'Close', 'data-dismiss' => 'modal', :type => 'button'}
          %span{'aria-hidden' => 'true'} &times;
      .modal-body
        %input.image_file{type: 'file'}
        %input.target_class{type: 'hidden'}
      .modal-footer
        %button.btn.btn-primary.btn_select{onclick: 'image_select.upload();'} 選択
        %button.btn.btn-light{'data-dismiss' => 'modal'} キャンセル
- content_for :javascript do
  = javascript_include_tag 'image_upload.js'

app/views/admin/images/_select.html.haml
- image_id = eval("f.object.#{target_id}")
- target_class ||= target_id
= link_to 'ファイルを選択', new_admin_image_path(target_id: target_id, target_class: target_class), remote: true, class: 'btn btn-info btn-sm btn-block'
= f.hidden_field target_id, class: target_class
.preview.mt-1{style: "display: #{image_id ? 'block' : 'none'}"}
  - if image_id
    = image_tag eval("f.object.#{target_id.to_s.slice(0, target_id.to_s.size-3)}.public_url(:thumb)"), width: '100%'
  - else
    %img{style: 'width: 100%;'}
  %p.text-right
    %a.image_clear{href: '#', onclick: 'file_clear(this);'}
      %i.fa.fa-times クリア

app/views/admin/images/new.js.erb
var modal = $('#image_select_dialog');
modal.find('.image_file').val('');
modal.find('.target_class').val('<%= @image.target_class %>');
var error_message = modal.find('.error_message');
<% if @image.errors.present? %>
    error_message.html('<%= @image.errors.full_messages[0] %>');
    error_message.css('display', 'block');
<% else %>
    error_message.css('display', 'none');
<% end %>
modal.modal({backdrop: 'static'});